apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-master-scaler
  namespace: opensearch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: akarx-cluster-master
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-data-scaler
  namespace: opensearch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: akarx-cluster-data
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
# Add more detailing to the HPA and make it more fine grained
