sparkJobNamespace: "spark-jobs"

logLevel: 4

podMonitor:
  # -- If enabled, a pod monitor for operator's pod will be submitted. Note that prometheus metrics should be enabled as well.
  enable: true
  # -- Pod monitor labels
  labels:
    spark-monitor: prometheus
