apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pgsql-deploy
  labels:
    app: node
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-pgsql
          image: node-pgsql-img:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_PORT
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
              # value: "5432"
            - name: POSTGRES_HOST
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
              # value: hippo-ha
            - name: POSTGRES_USER
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
              # value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
              # value: "]SR;Dbt0HzTFv4f3Wn}N)<8q"
            - name: POSTGRES_DB
              valueFrom:
                { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
              # value: hippo
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: node-pgsql-service
  labels:
    app: node
  namespace: postgres-operator
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: node-api
      nodePort: 30100
  selector:
    app: node
