apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-master-scaler
  namespace: opensearch-operator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: akarx-cluster-masters
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-data-scaler
  namespace: opensearch-operator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: akarx-cluster-data
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
# Add more detailing to the HPA and make it more fine grained
