apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: akarx-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
      class: longhorn
    # template:
    #   pod:
    #     affinity:
    #       nodeAffinity:
    #         requiredDuringSchedulingIgnoredDuringExecution:
    #           nodeSelectorTerms:
    #             - matchExpressions:
    #                 - key: kubernetes.io/hostname
    #                   operator: In
    #                   values:
    #                     - k8-4
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
      class: longhorn
    # template:
    #   pod:
    #     affinity:
    #       nodeAffinity:
    #         requiredDuringSchedulingIgnoredDuringExecution:
    #           nodeSelectorTerms:
    #             - matchExpressions:
    #                 - key: kubernetes.io/hostname
    #                   operator: In
    #                   values:
    #                     - k8-5
  entityOperator:
    topicOperator: {}
    userOperator: {}
