apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: akarx-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      class: kafka-storage
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      class: kafka-storage
  entityOperator:
    topicOperator: {}
    userOperator: {}
